// Catálogo editorial: no representa existencias, precios ni acuerdos de distribución.
// Fuentes oficiales y variantes revisadas el 2026-10-07. Confirmar SKU regional con proveedor.
export const catalogVersion = '0.2.0';
export const reviewedAt = '2026-10-07';
export const categories = [
  { id:'interior', name:'Cámaras de interior', icon:'⌂', description:'Para tu casa, mascotas y espacios interiores' },
  { id:'exterior', name:'Cámaras de exterior', icon:'◉', description:'Entradas y patios con conexión Wi-Fi' },
  { id:'bateria', name:'Batería y solar', icon:'☀', description:'Cámaras recargables sin enchufe permanente' },
  { id:'timbres', name:'Timbres y mirillas', icon:'♧', description:'Mira y atiende desde tu teléfono' },
  { id:'sensores', name:'Sensores y alarmas', icon:'⌁', description:'Movimiento, apertura y fugas de agua' },
  { id:'luces', name:'Iluminación inteligente', icon:'✧', description:'Ampolletas y tiras LED con control por app' },
  { id:'redes', name:'Wi-Fi y conectividad', icon:'⌘', description:'Extensores y sistemas de red Mesh' },
  { id:'accesorios', name:'Accesorios y memorias', icon:'▣', description:'Grabación local y carga solar compatible' }
];
export const installationLabels = {
  simple:'Enchufar y configurar', montaje:'Requiere fijación', bateria:'Batería recargable',
  puerta:'Revisar medidas de puerta', hub:'Requiere hub A3', accesorio:'Revisar compatibilidad'
};
const ez = (path) => 'https://www.ezviz.com/' + path;
const tp = (path) => 'https://www.tp-link.com/cl/home-networking/' + path + '/';
const photo = (name) => 'https://mfs.ezvizlife.com/' + name + '.jpg';
const s3 = (name) => 'https://s3.amazonaws.com/mfs.ezvizlife.com/' + name + '.jpg';
const rows = [
  ['ezviz-h1c','interior','EZVIZ','H1c 1080p','Cámara Wi-Fi compacta H1c', 'simple',
    'Una primera cámara para una repisa, el living o una habitación.',
    ['Full HD 1080p','Audio bidireccional','Visión nocturna infrarroja','Wi-Fi 2,4 GHz'],
    ['Necesita enchufe y adaptador de alimentación. No tiene batería.','Configura con la app EZVIZ. Para grabar localmente necesitas una microSD, no incluida.'],
    ['Conecta la cámara a la corriente.','Agrégala en EZVIZ y conéctala a tu Wi-Fi de 2,4 GHz.','Prueba el encuadre y configura las alertas.'],
    ez('la/product/H1c/50221'),photo('f020b1f24dadbaa736020672c9731831')],
  ['ezviz-h6c-4mp','interior','EZVIZ','H6c 2K+ · 4 MP','Cámara giratoria H6c 2K+', 'simple',
    'Para explorar el interior desde el celular y seguir el movimiento de personas.',
    ['4 MP · 2560 × 1440','Giro motorizado','Seguimiento inteligente','Wi-Fi 2,4 GHz'],
    ['Esta ficha corresponde a H6c 2K+ de 4 MP, no a otras variantes H6c.','Requiere alimentación permanente y app EZVIZ; microSD opcional no incluida.'],
    ['Conecta el adaptador a un enchufe.','Vincula la cámara mediante EZVIZ.','Ajusta el giro, la privacidad y las notificaciones.'],
    ez('la/product/H6c-2K%E2%81%BA/44053'),photo('440cecf7c6f38e94c6827ab67a4e464b')],
  ['ezviz-c6n-3mp','interior','EZVIZ','C6N · 3 MP','Cámara giratoria C6N 3 MP', 'simple',
    'Una alternativa de interior para revisar distintos ángulos desde la app.',
    ['3 MP · 2304 × 1296','Seguimiento de movimiento','Audio bidireccional','Wi-Fi 2,4 GHz'],
    ['Necesita enchufe; no es una cámara a batería.','Variante de 3 MP. La memoria microSD se compra por separado.'],
    ['Apoya la base sobre una superficie estable.','Conecta la alimentación y vincula la app EZVIZ.','Configura giro, alertas y almacenamiento.'],
    ez('la/product/C6N-3MP/37773'),s3('440cecf7c6f38e94c6827ab67a4e464b')],
  ['tapo-c210','interior','Tapo','C210 · 3 MP','Cámara giratoria Tapo C210', 'simple',
    'Una opción de interior para quienes prefieren el ecosistema Tapo.',
    ['3 MP · 2304 × 1296','Panorámica y movimiento vertical','Audio bidireccional','Wi-Fi 2,4 GHz'],
    ['Funciona con la app Tapo, no con la app EZVIZ.','Necesita adaptador conectado al enchufe; microSD no incluida.'],
    ['Conecta la cámara a la corriente.','Añádela siguiendo la app Tapo.','Elige alertas y comprueba la vista en directo.'],
    tp('cloud-camera/tapo-c210'),'https://static.tp-link.com/1_normal_1616234980592x.jpg'],
  ['ezviz-h3c-2k','exterior','EZVIZ','H3c 2K · 3 MP','Cámara exterior fija H3c 2K', 'montaje',
    'Para observar una entrada o un sector del patio con encuadre fijo.',
    ['2K · 3 MP','Protección IP67','Audio bidireccional','Wi-Fi 2,4 GHz'],
    ['Requiere fijación con tornillos y alimentación eléctrica permanente. Wi-Fi no significa sin cables.','Protege el adaptador y las conexiones según el manual; comprueba la señal antes de perforar.'],
    ['Vincula y prueba la señal a nivel de suelo.','Fija el soporte en una ubicación segura.','Conecta la alimentación y ajusta encuadre y detección.'],
    ez('la/product/H3c-2K/57547'),photo('c44d8f4868ccee8ef1335628dbf34f19')],
  ['ezviz-h8c-2k','exterior','EZVIZ','H8c 2K · 3 MP','Cámara exterior giratoria H8c 2K', 'montaje',
    'Para recorrer visualmente el acceso y el patio desde el celular.',
    ['2K · 3 MP','Giro y seguimiento de personas','Audio bidireccional','Wi-Fi 2,4 GHz'],
    ['Versión Wi-Fi, no PoE. Requiere enchufe y fijación.','No tiene batería. Comprueba cobertura Wi-Fi y protege las conexiones.'],
    ['Configura EZVIZ antes del montaje.','Comprueba el ángulo y fija la base de forma segura.','Conecta la alimentación y configura zonas de detección.'],
    ez('la/product/H8c-2K/46965'),photo('198c74d09cc8b089767366a34f5d8152')],
  ['ezviz-h9c-dual','exterior','EZVIZ','H9c Dual · 2K + 2K','Cámara exterior H9c Dual', 'montaje',
    'Dos vistas complementarias para observar un sector fijo y otro con giro.',
    ['Dos lentes de 2K','Detección de personas y vehículos','Seguimiento motorizado','Wi-Fi 2,4 GHz'],
    ['Es una cámara alimentada por adaptador, no por batería.','Necesita montaje y señal Wi-Fi en el lugar; verifica la variante Dual 2K.'],
    ['Vincula la cámara y verifica ambas vistas.','Fija el soporte sin trabajar en altura sin ayuda adecuada.','Ajusta las áreas de detección desde EZVIZ.'],
    ez('la/product/H9c-Dual-2K/60261'),photo('073776431d630895e1e9d72b079ae733')],
  ['tapo-c320ws','exterior','Tapo','C320WS · 4 MP','Cámara exterior Tapo C320WS', 'montaje',
    'Una alternativa de exterior con grabación local y conexión Wi-Fi o Ethernet.',
    ['4 MP · 2560 × 1440','Protección IP66','Visión nocturna en color','Audio bidireccional'],
    ['Necesita alimentación y soporte fijado; no es inalámbrica en energía.','Wi-Fi 2,4 GHz. Usa Tapo; microSD no incluida.'],
    ['Añade la cámara en Tapo y verifica la señal.','Fija el soporte y protege las conexiones.','Configura encuadre y alertas.'],
    tp('cloud-camera/tapo-c320ws'),'https://static.tp-link.com/upload/image-line/TapoC320WS_EU_1.0_01_normal_20210806074340s.png'],
  ['ezviz-cb3','bateria','EZVIZ','CB3 · 1080p','Cámara a batería CB3', 'bateria',
    'Para lugares con Wi-Fi donde no quieres llevar un cable eléctrico permanente.',
    ['Full HD 1080p','Batería de 5200 mAh','Detección de personas','Wi-Fi 2,4 GHz'],
    ['Requiere recargas; la autonomía depende del uso y la señal. No se promete grabación continua 24/7.','Panel solar opcional: confirmar compatibilidad y conector antes de comprar.'],
    ['Carga la batería y vincula EZVIZ.','Prueba la señal antes de fijarla.','Ajusta alertas y programa la revisión de batería.'],
    ez('la/product/cb3/44057'),photo('e7707198f203ba3f6c05df55936987bf')],
  ['ezviz-cb8','bateria','EZVIZ','CB8 · 2K','Cámara giratoria a batería CB8', 'bateria',
    'Una cámara recargable con movimiento para mirar distintos sectores exteriores.',
    ['2K · 3 MP','Batería de 10400 mAh','Giro y seguimiento','Wi-Fi 2,4 GHz'],
    ['Necesita recargas y fijación segura. Autonomía variable según actividad y configuración.','Panel solar y microSD se adquieren por separado; confirmar compatibilidad.'],
    ['Carga la cámara y enlázala en EZVIZ.','Prueba la cobertura y fija el soporte.','Ajusta la detección y revisa periódicamente la batería.'],
    ez('la/product/cb8/41159'),s3('4e8003189c2f5c4b62ead3cf798b847b')],
  ['ezviz-bc1c-4k','bateria','EZVIZ','BC1c 4K · Type-C','Cámara a batería BC1c 4K', 'bateria',
    'Alternativa de mayor resolución, sujeta a disponibilidad de esta versión regional.',
    ['4K · 8 MP','Batería de 10400 mAh','Wi-Fi 6 en 2,4 GHz','Protección IP65'],
    ['Ficha de la versión Type-C de España. Disponibilidad y SKU para Chile sin confirmar.','Adaptador de carga 5 V / 2 A se compra por separado. No confundir con versiones antiguas BC1c.'],
    ['Comprueba la versión y el cargador compatible.','Carga y vincula la app EZVIZ.','Prueba la señal y utiliza una base segura.'],
    ez('es/product/bc1c%2B4k/57921'),photo('419447a6fc278fcf2bc56c2c7b35c27a')],
  ['ezviz-dp2c','timbres','EZVIZ','DP2C','Mirilla digital DP2C con pantalla', 'puerta',
    'Mira quién llama desde la pantalla interior o desde tu teléfono.',
    ['Video Full HD 1080p','Pantalla interior de 4,3 pulgadas','Batería recargable','Wi-Fi 2,4 GHz'],
    ['Puerta compatible: grosor 35–105 mm y orificio de mirilla de 16,5–50 mm.','Requiere montaje en puerta y recargas. No altera ni sustituye la cerradura.'],
    ['Mide el grosor y el orificio existente.','Instala las piezas siguiendo el manual; solicita ayuda si no coincide.','Carga y vincula EZVIZ.'],
    ez('es/product/dp2c/40069'),s3('d6aba39be9e37df8062eff4f08fb52bd')],
  ['ezviz-db2-pro','timbres','EZVIZ','DB2 Pro','Kit de timbre con cámara DB2 Pro', 'bateria',
    'Para atender visitas con un timbre exterior recargable y campanilla interior.',
    ['Video 2K+','Batería de 5200 mAh','Campanilla incluida','Audio bidireccional'],
    ['Timbre a batería; la campanilla necesita enchufe. Requiere fijación en el acceso.','Wi-Fi 2,4 GHz. La microSD opcional se instala en la campanilla.'],
    ['Carga el timbre y conecta la campanilla.','Vincula las piezas mediante EZVIZ.','Prueba cobertura antes de fijar el timbre.'],
    ez('la/product/DB2-Pro/42435'),s3('f6a3b42474eefe13047add4b7b3c89c3')],
  ['ezviz-a3','sensores','EZVIZ','A3 Home Gateway','Hub para sensores EZVIZ A3', 'simple',
    'La central que conecta sensores compatibles EZVIZ con la app.',
    ['Hasta 64 dispositivos compatibles','Conexión Wi-Fi o Ethernet','Alertas sonoras','App EZVIZ'],
    ['Requiere alimentación y red. Los sensores se venden por separado.','No se garantiza compatibilidad con sensores Zigbee de cualquier otra marca.'],
    ['Conecta el hub a corriente y a la red.','Agrégalo en la app EZVIZ.','Vincula cada sensor compatible.'],
    ez('la/product/a3-home-gateway/41743'),s3('90e612d8b6baa8e54219ee41e0c9d4db')],
  ['ezviz-t1c','sensores','EZVIZ','T1C','Sensor de movimiento T1C', 'hub',
    'Detecta movimiento en un espacio interior sin llevar cableado al sensor.',
    ['Detección PIR','Funcionamiento a pila','Montaje adhesivo','Enlace Zigbee'],
    ['Requiere hub EZVIZ A3, vendido por separado, para notificaciones en la app.','Sensor para interior; no se conecta directamente al Wi-Fi.'],
    ['Configura primero el hub A3.','Vincula el sensor y prueba su área de detección.','Fíjalo siguiendo la altura y orientación del manual.'],
    ez('la/product/t1c-pir-motion-sensor/41741'),s3('d09bba68007f97efe319c4245785dd7d')],
  ['ezviz-t2c','sensores','EZVIZ','T2C','Sensor de apertura T2C', 'hub',
    'Recibe alertas de apertura en puertas o ventanas compatibles con el montaje.',
    ['Detección de apertura y cierre','Dos piezas adhesivas','Funcionamiento a pila','Enlace Zigbee'],
    ['Requiere hub EZVIZ A3, no incluido.','Debes alinear sensor e imán según el manual; no es un sensor Wi-Fi autónomo.'],
    ['Añade el sensor al hub A3.','Prueba la alineación antes de pegarlo.','Fija las dos piezas y comprueba una apertura.'],
    ez('la/product/T2C-Open-Close-Sensor/41739'),s3('7c68cd462d94edaf0f5db01f63120902')],
  ['ezviz-t10c','sensores','EZVIZ','T10C','Sensor de fugas de agua T10C', 'hub',
    'Para detectar agua cerca de una lavadora, lavaplatos o zona de riesgo.',
    ['Detección de agua','Protección IP67','Pila CR2032','Enlace Zigbee'],
    ['Requiere hub EZVIZ A3 para alertas y notificaciones; vendido por separado.','Detecta agua: no corta automáticamente el suministro.'],
    ['Empareja el sensor con A3.','Ubícalo en la zona baja que deseas revisar.','Prueba su funcionamiento según el manual.'],
    ez('la/product/t10c/63269'),photo('2339235178f9e51c148b0d39ea6d3cd1')],
  ['tapo-l530e','luces','Tapo','L530E · pack de 4','Ampolletas inteligentes L530E', 'simple',
    'Un pack para controlar color y horarios de varias luces desde Tapo.',
    ['4 ampolletas E27','Luz multicolor regulable','Wi-Fi 2,4 GHz','No requiere hub'],
    ['Confirmar pack y versión E27 de 220–240 V con el proveedor antes de vender.','Colocar con la alimentación cortada en un portalámparas compatible. Para control remoto, dejar el interruptor encendido.'],
    ['Con la corriente cortada, reemplaza la ampolleta compatible.','Restablece la alimentación.','Vincula en Tapo y define escenas y horarios.'],
    tp('smart-bulb/tapo-l530e'),'https://static.tp-link.com/upload/image-line/L530E-4Pack-Overview-01_normal_20220630080243l.jpg'],
  ['tapo-l900-5','luces','Tapo','L900-5 · 5 m','Tira LED inteligente L900-5', 'simple',
    'Iluminación decorativa para muebles y espacios interiores, controlada desde la app.',
    ['Longitud de 5 metros','Multicolor','Adhesivo de montaje','Wi-Fi 2,4 GHz · sin hub'],
    ['Requiere enchufe para el adaptador. Uso interior en un lugar apropiado y seco.','Comprueba el funcionamiento antes de pegar; corta solo en las marcas indicadas por el fabricante.'],
    ['Prueba la tira conectada a su adaptador.','Limpia la superficie y fija el adhesivo sin dañar la tira.','Vincula Tapo y ajusta color y horarios.'],
    tp('smart-bulb/tapo-l900-5'),'https://static.tp-link.com/upload/image-line/Tapo_L900-5%28EU%291.0-Web-2_normal_20230224071723q.jpg'],
  ['tplink-re305','redes','TP-Link','RE305 V3 · AC1200','Extensor de cobertura Wi-Fi RE305', 'simple',
    'Para llevar la señal de tu router más cerca de los dispositivos inteligentes.',
    ['Doble banda 2,4 y 5 GHz','Clase Wi-Fi AC1200','Indicador de señal','Configuración con Tether'],
    ['Necesita enchufe y una red Wi-Fi existente; no incluye servicio de internet.','Ubícalo donde todavía reciba buena señal. Verificar tipo de enchufe de la versión regional.'],
    ['Conecta cerca del router para configurarlo.','Vincula con Tether o el método del manual.','Reubícalo usando el indicador de señal.'],
    tp('range-extender/re305'),'https://static.tp-link.com/RE305-01_1487555835366q.jpg'],
  ['tplink-deco-e4','redes','TP-Link','Deco E4 · pack de 3','Sistema Wi-Fi Mesh Deco E4', 'simple',
    'Tres nodos para ampliar la cobertura del hogar con una sola red.',
    ['Pack de 3 unidades','Wi-Fi AC1200 de doble banda','Configuración con app Deco','Puertos Ethernet de 100 Mbps'],
    ['No tiene puertos Gigabit: puede limitar conexiones de internet superiores a 100 Mbps.','Cada nodo necesita enchufe; el principal se conecta al módem/router por Ethernet. Confirmar pack regional.'],
    ['Conecta el Deco principal a corriente y al módem/router.','Sigue la app Deco.','Añade y distribuye los otros dos nodos probando cobertura.'],
    tp('deco/deco-e4'),'https://static.tp-link.com/upload/image-line/Deco_E4%282-pack%29_EU_V1.0_01_normal_20220828090106o.jpg'],
  ['ezviz-panel-d','accesorios','EZVIZ','Solar Panel D','Panel de carga solar EZVIZ D', 'accesorio',
    'Un accesorio de carga para cámaras EZVIZ a batería expresamente compatibles.',
    ['Potencia máxima de 4,2 W','Cable de 4 metros','Soporte ajustable','Protección IP65'],
    ['Confirmar modelo de cámara, puerto y compatibilidad en el manual. No es universal.','Requiere fijación y exposición al sol. El rendimiento cambia con el clima; no garantiza autonomía ilimitada.'],
    ['Confirma compatibilidad del panel y la cámara.','Elige una ubicación soleada y segura.','Fija y conecta de acuerdo con el manual.'],
    ez('la/product/solar%2Bcharging%2Bpanel-d/42439'),s3('364c4377abdbffb1051b44c07dc87972')],
  ['ezviz-panel-f','accesorios','EZVIZ','Solar Panel F · Type-C','Panel de carga solar EZVIZ F', 'accesorio',
    'Carga solar para versiones compatibles con conexión Type-C.',
    ['Conexión Type-C','Potencia máxima de 4,2 W','Cable de 4 metros','Protección IP65'],
    ['El conector Type-C no asegura por sí solo compatibilidad: verificar cámara y variante exacta.','Necesita montaje y sol suficiente; no sustituye la red Wi-Fi ni garantiza grabación continua.'],
    ['Revisa el modelo en la lista de compatibilidad.','Prueba la conexión antes de fijar el soporte.','Orienta hacia una zona despejada y revisa la carga.'],
    ez('la/product/Solar-Charging-Panel-F/47579'),photo('68845ad306b89474bc08eb1c14f92ff2')],
  ['sandisk-endurance-128','accesorios','SanDisk','High Endurance · 128 GB','Memoria microSD High Endurance', 'accesorio',
    'Almacenamiento pensado para grabar y regrabar video en cámaras compatibles.',
    ['Capacidad de 128 GB','microSDXC UHS-I','Clase 10 · U3 · V30','Diseñada para grabación repetida'],
    ['Verifica que tu cámara admita microSDXC de 128 GB y formatea desde su app.','El tiempo de video conservado depende de resolución, compresión y tipo de grabación.'],
    ['Apaga la cámara según el manual antes de insertar la tarjeta.','Enciende y formatea desde su aplicación.','Comprueba que una grabación pueda reproducirse.'],
    'https://www.sandisk.com/es-la/products/memory-cards/microsd-cards/sandisk-high-endurance-uhs-i-microsd','https://www.sandisk.com/content/dam/store/en-us/assets/products/memory-cards/high-endurance-uhs-i-microsd/gallery/high-endurance-uhs-i-microsd-128gb-front.png.wdthumb.1280.1280.png']
];
export const products = rows.map(([id,category,brand,model,name,installation,description,features,requirements,steps,source,image]) => ({
  id, category, brand, model, sku:id.toUpperCase(), name, installation, description, features, requirements, steps, source, image,
  reviewedAt, price:null, stock:null, pricingStatus:'pending', availabilityStatus:'unconfirmed',
  requiresHub:installation==='hub', app:brand==='EZVIZ'?'EZVIZ':brand==='Tapo'?'Tapo':brand==='TP-Link'?(id.includes('deco')?'Deco':'Tether'):null
}));
